version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tester2
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis
    depends_on:
      - db
    ports:
      - '6379:6379'
  web:
    image: full-stack-api:latest
    depends_on:
      - db
      - redis
    ports:
      - '12000:12000'
